name: Pull Data

on: [workflow_dispatch]

jobs:
  check_for_data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./data_retrieval/requirements.txt
    - name: Get and check data
      run: |
        python data_retrieval/check_new_data.py
